local languages = {
    markdownH1 = {fg = C.red, bg = C.none, style = "bold", },
    markdownH2 = {fg = C.orange, bg = C.none, style = "bold", },
    markdownH3 = {fg = C.yellow, bg = C.none, style = "bold", },
    markdownH4 = {fg = C.green, bg = C.none, style = "bold", },
    markdownH5 = {fg = C.blue, bg = C.none, style = "bold", },
    markdownH6 = {fg = C.purple, bg = C.none, style = "bold", },
    markdownUrl = {fg = C.blue, bg = C.none, style = "underline", },
    markdownItalic = {fg = C.none, bg = C.none, style = "italic", },
    markdownBold = {fg = C.none, bg = C.none, style = "bold", },
    markdownItalicDelimiter = {fg = C.grey1, bg = C.none, style = "italic", },
    markdownCode = {fg = C.green, bg = C.none, },
    markdownCodeBlock = {fg = C.aqua, bg = C.none, },
    markdownCodeDelimiter = {fg = C.aqua, bg = C.none, },
    markdownBlockquote = {fg = C.grey1, bg = C.none, },
    markdownListMarker = {fg = C.red, bg = C.none, },
    markdownOrderedListMarker = {fg = C.red, bg = C.none, },
    markdownRule = {fg = C.purple, bg = C.none, },
    markdownHeadingRule = {fg = C.grey1, bg = C.none, },
    markdownUrlDelimiter = {fg = C.grey1, bg = C.none, },
    markdownLinkDelimiter = {fg = C.grey1, bg = C.none, },
    markdownLinkTextDelimiter = {fg = C.grey1, bg = C.none, },
    markdownHeadingDelimiter = {fg = C.grey1, bg = C.none, },
    markdownLinkText = {fg = C.purple, bg = C.none, },
    markdownUrlTitleDelimiter = {fg = C.green, bg = C.none, },
    markdownIdDeclaration = {fg = C.grey1, bg = C.none, },
    markdownBoldDelimiter = {fg = C.grey1, bg = C.none, },
    markdownId = {fg = C.yellow, bg = C.none, },

    htmlH1 = {fg = C.red, bg = C.none, style = "bold", },
    htmlH2 = {fg = C.orange, bg = C.none, style = "bold", },
    htmlH3 = {fg = C.yellow, bg = C.none, style = "bold", },
    htmlH4 = {fg = C.green, bg = C.none, style = "bold", },
    htmlH5 = {fg = C.blue, bg = C.none, style = "bold", },
    htmlH6 = {fg = C.purple, bg = C.none, style = "bold", },
    htmlLink = {fg = C.none, bg = C.none, style = "underline", },
    htmlBold = {fg = C.none, bg = C.none, style = "bold", },
    htmlBoldUnderline = {fg = C.none, bg = C.none, style = "bold,underline", },
    htmlBoldItalic = {fg = C.none, bg = C.none, style = "bold,italic", },
    htmlBoldUnderlineItalic = {fg = C.none, bg = C.none, style = "bold,underline,italic", },
    htmlUnderline = {fg = C.none, bg = C.none, style = "underline", },
    htmlUnderlineItalic = {fg = C.none, bg = C.none, style = "underline,italic", },
    htmlItalic = {fg = C.none, bg = C.none, style = "italic", },
    htmlTag = {fg = C.green, bg = C.none, },
    htmlEndTag = {fg = C.blue, bg = C.none, },
    htmlTagN = {fg = C.orange, bg = C.none, style = "italic", },
    htmlTagName = {fg = C.orange, bg = C.none, style = "italic", },
    htmlArg = {fg = C.aqua, bg = C.none, },
    htmlScriptTag = {fg = C.purple, bg = C.none, },
    htmlSpecialTagName = {fg = C.red, bg = C.none, style = "italic", },
}

return languages
