local config = require("gruvqueen.config")
local c = require("gruvqueen.palette")

local treesitter = {
    TSStrong = {fg = c.none, bg = c.none, style = config.disable_bold and "NONE" or "bold", },
    TSEmphasis = {fg = c.none, bg = c.none, style = config.disable_bold and "NONE" or "bold", },
    TSUnderline = {fg = c.none, bg = c.none, style = "underline", },
    TSNote = {fg = c.bg0, bg = c.blue, style = config.disable_bold and "NONE" or "bold", },
    TSWarning = {fg = c.bg0, bg = c.yellow, style = config.disable_bold and "NONE" or "bold", },
    TSDanger = {fg = c.bg0, bg = c.red, style = config.disable_bold and "NONE" or "bold", },
    TSAnnotation = {fg = c.purple, bg = c.none, },
    TSAttribute = {fg = c.purple, bg = c.none, },
    TSBoolean = {fg = c.purple, bg = c.none, },
    TSCharacter = {fg = c.aqua, bg = c.none, },
    TSComment = {fg = c.grey1, bg = c.none, style = "italic", },
    TSConditional = {fg = c.red, bg = c.none, },
    TSConstBuiltin = {fg = c.blue, bg = c.none, style = "italic", },
    TSConstMacro = {fg = c.blue, bg = c.none, style = "italic", },
    TSConstant = {fg = c.fg0, bg = c.none, },
    TSConstructor = {fg = c.fg0, bg = c.none, },
    TSException = {fg = c.red, bg = c.none, },
    TSField = {fg = c.green, bg = c.none, },
    TSFloat = {fg = c.purple, bg = c.none, },
    TSFuncBuiltin = {fg = c.green, bg = c.none, style = config.disable_bold and "NONE" or "bold", },
    TSFuncMacro = {fg = c.green, bg = c.none, style = config.disable_bold and "NONE" or "bold", },
    TSFunction = {fg = c.green, bg = c.none, style = config.disable_bold and "NONE" or "bold", },
    TSInclude = {fg = c.red, bg = c.none, },
    TSKeyword = {fg = c.red, bg = c.none, },
    TSKeywordFunction = {fg = c.red, bg = c.none, },
    TSKeywordOperator = {fg = c.orange, bg = c.none, },
    TSLabel = {fg = c.orange, bg = c.none, },
    TSMethod = {fg = c.green, bg = c.none, style = config.disable_bold and "NONE" or "bold", },
    TSNamespace = {fg = c.yellow, bg = c.none, style = "italic", },
    TSNone = {fg = c.fg0, bg = c.none, },
    TSNumber = {fg = c.purple, bg = c.none, },
    TSOperator = {fg = c.orange, bg = c.none, },
    TSParameter = {fg = c.fg0, bg = c.none, },
    TSParameterReference = {fg = c.fg0, bg = c.none, },
    TSProperty = {fg = c.green, bg = c.none, },
    TSPunctBracket = {fg = c.fg0, bg = c.none, },
    TSPunctDelimiter = {fg = c.grey1, bg = c.none, },
    TSPunctSpecial = {fg = c.blue, bg = c.none, },
    TSRepeat = {fg = c.red, bg = c.none, },
    TSString = {fg = c.aqua, bg = c.none, },
    TSStringEscape = {fg = c.green, bg = c.none, },
    TSStringRegex = {fg = c.green, bg = c.none, },
    TSStructure = {fg = c.blue, bg = c.none, style = "italic", },
    TSSymbol = {fg = c.fg0, bg = c.none, },
    TSTag = {fg = c.orange, bg = c.none, },
    TSTagDelimiter = {fg = c.green, bg = c.none, },
    TSText = {fg = c.green, bg = c.none, },
    TSStrike = {fg = c.grey1, bg = c.none, },
    TSMath = {fg = c.blue, bg = c.none, },
    TSType = {fg = c.yellow, bg = c.none, },
    TSTypeBuiltin = {fg = c.yellow, bg = c.none, style = "italic", },
    TSURI = {fg = c.blue, bg = c.none, style = "underline", },
    TSVariable = {fg = c.fg0, bg = c.none, },
    TSVariableBuiltin = {fg = c.blue, bg = c.none, style = "italic", },
}

return treesitter
