local function init(c, config)
    local treesitter = {
        TSStrong = {fg = c.none, style = config.disable_bold and "NONE" or "bold", },
        TSEmphasis = {fg = c.none, style = config.disable_bold and "NONE" or "bold", },
        TSUnderline = {fg = c.none, style = "underline", },
        TSNote = {fg = c.bg0, bg = c.blue, style = config.disable_bold and "NONE" or "bold", },
        TSWarning = {fg = c.bg0, bg = c.yellow, style = config.disable_bold and "NONE" or "bold", },
        TSDanger = {fg = c.bg0, bg = c.red, style = config.disable_bold and "NONE" or "bold", },
        TSAnnotation = {fg = c.purple, },
        TSAttribute = {fg = c.purple, },
        TSBoolean = {fg = c.purple, },
        TSCharacter = {fg = c.aqua, },
        TSComment = {fg = c.grey1, style = "italic", },
        TSConditional = {fg = c.red, },
        TSConstBuiltin = {fg = c.blue, style = "italic", },
        TSConstMacro = {fg = c.blue, style = "italic", },
        TSConstant = {fg = c.fg0, },
        TSConstructor = {fg = c.fg0, },
        TSException = {fg = c.red, },
        TSField = {fg = c.green, },
        TSFloat = {fg = c.purple, },
        TSFuncBuiltin = {fg = c.green, style = config.disable_bold and "NONE" or "bold", },
        TSFuncMacro = {fg = c.green, style = config.disable_bold and "NONE" or "bold", },
        TSFunction = {fg = c.green, style = config.disable_bold and "NONE" or "bold", },
        TSInclude = {fg = c.red, },
        TSKeyword = {fg = c.red, },
        TSKeywordFunction = {fg = c.red, },
        TSKeywordOperator = {fg = c.orange, },
        TSLabel = {fg = c.orange, },
        TSMethod = {fg = c.green, style = config.disable_bold and "NONE" or "bold", },
        TSNamespace = {fg = c.yellow, style = "italic", },
        TSNone = {fg = c.fg0, },
        TSNumber = {fg = c.purple, },
        TSOperator = {fg = c.orange, },
        TSParameter = {fg = c.fg0, },
        TSParameterReference = {fg = c.fg0, },
        TSProperty = {fg = c.green, },
        TSPunctBracket = {fg = c.fg0, },
        TSPunctDelimiter = {fg = c.grey1, },
        TSPunctSpecial = {fg = c.blue, },
        TSRepeat = {fg = c.red, },
        TSString = {fg = c.aqua, },
        TSStringEscape = {fg = c.green, },
        TSStringRegex = {fg = c.green, },
        TSStructure = {fg = c.blue, style = "italic", },
        TSSymbol = {fg = c.fg0, },
        TSTag = {fg = c.orange, },
        TSTagDelimiter = {fg = c.green, },
        TSText = {fg = c.green, },
        TSStrike = {fg = c.grey1, },
        TSMath = {fg = c.blue, },
        TSType = {fg = c.yellow, },
        TSTypeBuiltin = {fg = c.yellow, style = "italic", },
        TSURI = {fg = c.blue, style = "underline", },
        TSVariable = {fg = c.fg0, },
        TSVariableBuiltin = {fg = c.blue, style = "italic", },
    }

    return treesitter
end

return {init = init}
