local treesitter = {
    TSStrong = {fg = C.none, bg = C.none, style = "bold", },
    TSEmphasis = {fg = C.none, bg = C.none, style = "bold", },
    TSUnderline = {fg = C.none, bg = C.none, style = "underline", },
    TSNote = {fg = C.bg0, bg = C.blue, style = "bold", },
    TSWarning = {fg = C.bg0, bg = C.yellow, style = "bold", },
    TSDanger = {fg = C.bg0, bg = C.red, style = "bold", },
    TSAnnotation = {fg = C.purple, bg = C.none, },
    TSAttribute = {fg = C.purple, bg = C.none, },
    TSBoolean = {fg = C.purple, bg = C.none, },
    TSCharacter = {fg = C.aqua, bg = C.none, },
    TSComment = {fg = C.grey1, bg = C.none, style = "italic", },
    TSConditional = {fg = C.red, bg = C.none, },
    TSConstBuiltin = {fg = C.blue, bg = C.none, style = "italic", },
    TSConstMacro = {fg = C.blue, bg = C.none, style = "italic", },
    TSConstant = {fg = C.fg0, bg = C.none, },
    TSConstructor = {fg = C.fg0, bg = C.none, },
    TSException = {fg = C.red, bg = C.none, },
    TSField = {fg = C.green, bg = C.none, },
    TSFloat = {fg = C.purple, bg = C.none, },
    TSFuncBuiltin = {fg = C.green, bg = C.none, style = "bold", },
    TSFuncMacro = {fg = C.green, bg = C.none, style = "bold", },
    TSFunction = {fg = C.green, bg = C.none, style = "bold", },
    TSInclude = {fg = C.red, bg = C.none, },
    TSKeyword = {fg = C.red, bg = C.none, },
    TSKeywordFunction = {fg = C.red, bg = C.none, },
    TSKeywordOperator = {fg = C.orange, bg = C.none, },
    TSLabel = {fg = C.orange, bg = C.none, },
    TSMethod = {fg = C.green, bg = C.none, style = "bold", },
    TSNamespace = {fg = C.yellow, bg = C.none, style = "italic", },
    TSNone = {fg = C.fg0, bg = C.none, },
    TSNumber = {fg = C.purple, bg = C.none, },
    TSOperator = {fg = C.orange, bg = C.none, },
    TSParameter = {fg = C.fg0, bg = C.none, },
    TSParameterReference = {fg = C.fg0, bg = C.none, },
    TSProperty = {fg = C.green, bg = C.none, },
    TSPunctBracket = {fg = C.fg0, bg = C.none, },
    TSPunctDelimiter = {fg = C.grey1, bg = C.none, },
    TSPunctSpecial = {fg = C.blue, bg = C.none, },
    TSRepeat = {fg = C.red, bg = C.none, },
    TSString = {fg = C.aqua, bg = C.none, },
    TSStringEscape = {fg = C.green, bg = C.none, },
    TSStringRegex = {fg = C.green, bg = C.none, },
    TSStructure = {fg = C.blue, bg = C.none, style = "italic", },
    TSSymbol = {fg = C.fg0, bg = C.none, },
    TSTag = {fg = C.orange, bg = C.none, },
    TSTagDelimiter = {fg = C.green, bg = C.none, },
    TSText = {fg = C.green, bg = C.none, },
    TSStrike = {fg = C.grey1, bg = C.none, },
    TSMath = {fg = C.blue, bg = C.none, },
    TSType = {fg = C.yellow, bg = C.none, },
    TSTypeBuiltin = {fg = C.yellow, bg = C.none, style = "italic", },
    TSURI = {fg = C.blue, bg = C.none, style = "underline", },
    TSVariable = {fg = C.fg0, bg = C.none, },
    TSVariableBuiltin = {fg = C.blue, bg = C.none, style = "italic", },
}

return treesitter
